services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
